"""Core domain models, parser, and graph engine for SpecOps."""

from .ast_parser import FrontmatterDiagnosticError, parse_markdown_document
from .cache import CompileStats, RelationalGraphCacheEngine
from .git_metadata import GitMetadataHarvester
from .graph import (
    build_graph_data,
    compute_health_metrics,
    generate_traceability_edges,
    process_project_graph,
)
from .models import (
    ADR,
    PRD,
    CommitInfo,
    GraphData,
    GraphEdge,
    GraphNode,
    Persona,
    ProjectData,
    Task,
    TraceabilityEdge,
    UserStory,
)
from .parser import SpecOpsParser, extract_frontmatter

from .event_bus import (
    BATCHED_UPDATE,
    GRAPH_CYCLE_INTRODUCED,
    NODE_UPDATED,
    TASK_PROMOTED,
    UNANCHORED_REFERENCE_DETECTED,
    Debouncer,
    EventBus,
    GraphEvent,
    InMemoryGraphState,
)
from .graph_audit import audit_bottlenecks, audit_graph_all, audit_traceability
from .pathfinder import find_shortest_traceability_path, format_traceability_path, inspect_entity
from .topology import (
    BlastRadiusResult,
    CycleResult,
    DirectedGraph,
    TopologicalTierResult,
    compute_blast_radius,
    compute_execution_tiers,
    detect_cycles,
    kahns_topological_sort,
    tarjan_scc,
)
from .cycle_resolver import (
    ChokePoint,
    CycleResolution,
    calculate_choke_points,
    find_minimal_feedback_arc_set,
    format_choke_points,
    format_cycle_resolutions,
    resolve_cyclic_components,
    suggest_decoupling_seams,
)
from .event_store import SQLiteEventLedger, append_events, get_stream, project_task_event_to_filesystem, replay_task_state
from .event_streamer import EventEnvelope, EventStreamer, get_event_streamer, reset_event_streamers
from .watcher import WorkspaceWatcher
from .dag_cache import (
    CyclePreCheckResult,
    CyclicDependencyError,
    DAGCacheEngine,
    DAGCachePayload,
    can_add_dependency,
)
from .audit_sink import (
    AuditEntry,
    AuditFilter,
    AuditSinkExporter,
    read_audit_sink,
    verify_audit_sink,
)

__all__ = [
    "ADR",
    "CommitInfo",
    "CompileStats",
    "FrontmatterDiagnosticError",
    "GitMetadataHarvester",
    "GraphData",
    "GraphEdge",
    "GraphNode",
    "PRD",
    "Persona",
    "ProjectData",
    "RelationalGraphCacheEngine",
    "SpecOpsParser",
    "Task",
    "TraceabilityEdge",
    "UserStory",
    "build_graph_data",
    "compute_health_metrics",
    "extract_frontmatter",
    "generate_traceability_edges",
    "parse_markdown_document",
    "process_project_graph",
    "DirectedGraph",
    "CycleResult",
    "TopologicalTierResult",
    "BlastRadiusResult",
    "tarjan_scc",
    "detect_cycles",
    "CycleResolution",
    "ChokePoint",
    "find_minimal_feedback_arc_set",
    "resolve_cyclic_components",
    "calculate_choke_points",
    "suggest_decoupling_seams",
    "format_cycle_resolutions",
    "format_choke_points",
    "kahns_topological_sort",
    "compute_execution_tiers",
    "compute_blast_radius",
    "find_shortest_traceability_path",
    "format_traceability_path",
    "inspect_entity",
    "audit_traceability",
    "audit_bottlenecks",
    "audit_graph_all",
    "EventBus",
    "GraphEvent",
    "Debouncer",
    "InMemoryGraphState",
    "WorkspaceWatcher",
    "TASK_PROMOTED",
    "UNANCHORED_REFERENCE_DETECTED",
    "GRAPH_CYCLE_INTRODUCED",
    "NODE_UPDATED",
    "BATCHED_UPDATE",
    "SQLiteEventLedger",
    "append_events",
    "get_stream",
    "project_task_event_to_filesystem",
    "replay_task_state",
    "EventEnvelope",
    "EventStreamer",
    "get_event_streamer",
    "reset_event_streamers",
    "DAGCacheEngine",
    "DAGCachePayload",
    "CyclePreCheckResult",
    "CyclicDependencyError",
    "can_add_dependency",
    "AuditEntry",
    "AuditFilter",
    "AuditSinkExporter",
    "read_audit_sink",
    "verify_audit_sink",
    "ConsultedSpecReference",
    "SubagentConsultationRequest",
    "SubagentConsultationResponse",
    "SpecConsultationValidator",
    "ALL_DOR_GATE_RULES",
    "ALL_DOD_GATE_RULES",
    "DoRGateResult",
    "DoDGateResult",
    "LifecycleGateOrchestrator",
    "cleanup_worktree",
    "create_worktree",
    "get_worktree_branch",
    "init_worktree_environment",
    "is_worktree_dirty",
    "prune_git_worktrees",
    "register_default_hook_propagator",
]

from .subagent_consultation import (
    ConsultedSpecReference,
    SpecConsultationValidator,
    SubagentConsultationRequest,
    SubagentConsultationResponse,
)
from .lifecycle_gates import (
    ALL_DOD_GATE_RULES,
    ALL_DOR_GATE_RULES,
    DoDGateResult,
    DoRGateResult,
    LifecycleGateOrchestrator,
)
from .git_worktree import (
    cleanup_worktree,
    create_worktree,
    get_worktree_branch,
    init_worktree_environment,
    is_worktree_dirty,
    prune_git_worktrees,
    register_default_hook_propagator,
)

