"""SpecOps security bounded context: process sandboxing, interceptors, and guardrails."""

from __future__ import annotations

from .benchmark import run_comparative_benchmark
from .digest import compute_git_tree_digest
from .entropy_plugins import (
    EntropyFinding,
    EntropyRule,
    EntropyScannerConfig,
    ShannonEntropyScanner,
    calculate_entropy,
)
from .git_hooks import (
    HOOK_END_MARKER,
    HOOK_START_MARKER,
    HookSentinelResult,
    generate_hook_payload,
    inject_sentinel_block,
    install_hook,
    resolve_hooks_dir,
    run_hook_sentinel,
    strip_sentinel_block,
    uninstall_hook,
    verify_hook,
)
from .hygiene import assert_handover_excluded_from_git
from .interceptor import (
    FORBIDDEN_UTILITIES,
    create_interceptor_shims,
    extract_executables,
    extract_executables_with_context,
    record_security_violation,
    resolve_audit_log_path,
    validate_command,
)
from .lockfile import (
    PROTECTED_DEPENDENCY_FILES,
    LockfileInspectionResult,
    check_diff_for_dependency_modifications,
    check_worktree_dependency_integrity,
    inspect_lockfile,
    validate_package_hashes,
    validate_package_name,
    validate_package_pinning,
    verify_lockfile,
    verify_uv_lock,
)
from .lockfile_sentinel import (
    PROTECTED_LOCKFILES,
    LockfileSentinelResult,
    detect_lockfile_mutations,
    inspect_lockfile_sentinel,
    is_lockfile_mutation_waived,
    is_protected_lockfile,
    remediate_lockfile_mutations,
)
from .merkle import (
    ComplianceDeliverable,
    ComplianceManifest,
    HumanSignoff,
    MerkleInclusionProof,
    MerkleLeaf,
    MerkleTree,
    ProofStep,
    canonical_json_encode,
    compile_compliance_manifest,
    extract_repo_compliance_deliverables,
    hash_internal_node,
    hash_leaf,
    verify_compliance_manifest,
    verify_inclusion_proof,
)
from .merkle_manifest import (
    MerkleManifest,
    MerkleVerificationResult,
    build_merkle_manifest,
    collect_project_artifacts,
    generate_file_proof,
    generate_merkle_manifest,
    verify_file_proof,
    verify_merkle_manifest,
)
from .models import BenchmarkReport, BenchmarkResult, SecurityViolationEvent
from .network_guard import generate_network_isolation_sitecustomize, is_loopback_address, isolated_network
from .release_verifier import (
    AuthorizedSigner,
    ReleaseVerificationResult,
    parse_allowed_signers,
    sign_release_manifest,
    verify_release_manifest_data,
    verify_release_manifest_file,
)
from .sandbox import ExecutionSandbox
from .sandbox_env import (
    DEFAULT_TOOLCHAIN_ENV_VARS,
    is_sensitive_key,
    is_sensitive_value,
    sanitize_environment,
)
from .supply_chain_daemon import (
    LockfileAttestation,
    LockfileIntegrityReport,
    SupplyChainSentinel,
    compute_file_sha256,
    handle_audit_lockfile,
)
from .trailer_sanitizer import (
    CommitValidationResult,
    TrailerSanitizer,
    parse_rfc822_trailers,
)

__all__ = [
    "AuthorizedSigner",
    "BenchmarkReport",
    "BenchmarkResult",
    "CommitValidationResult",
    "ComplianceDeliverable",
    "ComplianceManifest",
    "assert_handover_excluded_from_git",
    "EntropyFinding",
    "EntropyRule",
    "EntropyScannerConfig",
    "ExecutionSandbox",
    "FORBIDDEN_UTILITIES",
    "HOOK_END_MARKER",
    "HOOK_START_MARKER",
    "HookSentinelResult",
    "HumanSignoff",
    "LockfileAttestation",
    "LockfileInspectionResult",
    "LockfileIntegrityReport",
    "LockfileSentinelResult",

    "MerkleInclusionProof",
    "MerkleLeaf",
    "MerkleManifest",
    "MerkleTree",
    "MerkleVerificationResult",
    "PROTECTED_DEPENDENCY_FILES",
    "PROTECTED_LOCKFILES",
    "ProofStep",
    "ReleaseVerificationResult",
    "SecurityViolationEvent",
    "ShannonEntropyScanner",
    "SupplyChainSentinel",
    "build_merkle_manifest",
    "calculate_entropy",
    "canonical_json_encode",
    "check_diff_for_dependency_modifications",
    "check_worktree_dependency_integrity",
    "collect_project_artifacts",
    "compile_compliance_manifest",
    "compute_file_sha256",
    "compute_git_tree_digest",
    "create_interceptor_shims",
    "detect_lockfile_mutations",
    "extract_executables",
    "extract_executables_with_context",
    "extract_repo_compliance_deliverables",
    "generate_file_proof",
    "generate_hook_payload",
    "generate_merkle_manifest",
    "generate_network_isolation_sitecustomize",
    "handle_audit_lockfile",
    "hash_internal_node",
    "hash_leaf",
    "inject_sentinel_block",
    "inspect_lockfile",
    "inspect_lockfile_sentinel",
    "install_hook",
    "is_lockfile_mutation_waived",
    "is_loopback_address",
    "is_protected_lockfile",
    "isolated_network",
    "TrailerSanitizer",
    "parse_allowed_signers",
    "parse_rfc822_trailers",
    "record_security_violation",
    "remediate_lockfile_mutations",
    "resolve_audit_log_path",
    "resolve_hooks_dir",
    "run_comparative_benchmark",
    "run_hook_sentinel",
    "sanitize_environment",
    "sign_release_manifest",
    "strip_sentinel_block",
    "uninstall_hook",
    "validate_command",
    "validate_package_hashes",
    "validate_package_name",
    "validate_package_pinning",
    "verify_compliance_manifest",
    "verify_file_proof",
    "verify_hook",
    "verify_inclusion_proof",
    "verify_lockfile",
    "verify_merkle_manifest",
    "verify_release_manifest_data",
    "verify_release_manifest_file",
    "verify_uv_lock",
]

