"""SpecOps security bounded context: process sandboxing, interceptors, and guardrails."""

from __future__ import annotations

from .benchmark import run_comparative_benchmark
from .interceptor import (
    FORBIDDEN_UTILITIES,
    create_interceptor_shims,
    extract_executables,
    extract_executables_with_context,
    record_security_violation,
    resolve_audit_log_path,
    validate_command,
)
from .lockfile import (
    PROTECTED_DEPENDENCY_FILES,
    LockfileInspectionResult,
    check_diff_for_dependency_modifications,
    check_worktree_dependency_integrity,
    inspect_lockfile,
    validate_package_hashes,
    validate_package_name,
    validate_package_pinning,
    verify_lockfile,
    verify_uv_lock,
)
from .lockfile_sentinel import (
    PROTECTED_LOCKFILES,
    LockfileSentinelResult,
    detect_lockfile_mutations,
    inspect_lockfile_sentinel,
    is_lockfile_mutation_waived,
    is_protected_lockfile,
    remediate_lockfile_mutations,
)
from .merkle import (
    ComplianceDeliverable,
    ComplianceManifest,
    HumanSignoff,
    MerkleInclusionProof,
    MerkleLeaf,
    MerkleTree,
    ProofStep,
    canonical_json_encode,
    compile_compliance_manifest,
    extract_repo_compliance_deliverables,
    hash_internal_node,
    hash_leaf,
    verify_compliance_manifest,
    verify_inclusion_proof,
)
from .models import BenchmarkReport, BenchmarkResult, SecurityViolationEvent
from .network_guard import generate_network_isolation_sitecustomize, is_loopback_address, isolated_network
from .sandbox import ExecutionSandbox

__all__ = [
    "FORBIDDEN_UTILITIES",
    "BenchmarkReport",
    "BenchmarkResult",
    "ComplianceDeliverable",
    "ComplianceManifest",
    "ExecutionSandbox",
    "HumanSignoff",
    "LockfileInspectionResult",
    "LockfileSentinelResult",
    "MerkleInclusionProof",
    "MerkleLeaf",
    "MerkleTree",
    "PROTECTED_DEPENDENCY_FILES",
    "PROTECTED_LOCKFILES",
    "ProofStep",
    "SecurityViolationEvent",
    "canonical_json_encode",
    "check_diff_for_dependency_modifications",
    "check_worktree_dependency_integrity",
    "compile_compliance_manifest",
    "create_interceptor_shims",
    "detect_lockfile_mutations",
    "extract_executables",
    "extract_executables_with_context",
    "extract_repo_compliance_deliverables",
    "generate_network_isolation_sitecustomize",
    "hash_internal_node",
    "hash_leaf",
    "inspect_lockfile",
    "inspect_lockfile_sentinel",
    "is_lockfile_mutation_waived",
    "is_loopback_address",
    "is_protected_lockfile",
    "isolated_network",
    "record_security_violation",
    "remediate_lockfile_mutations",
    "resolve_audit_log_path",
    "run_comparative_benchmark",
    "validate_command",
    "validate_package_hashes",
    "validate_package_name",
    "validate_package_pinning",
    "verify_compliance_manifest",
    "verify_inclusion_proof",
    "verify_lockfile",
    "verify_uv_lock",
]
